language: csharp
mono: none
dotnet: 1.0.0-preview2-003131
solution: GovITHub.Auth.Identity.sln
dist: trusty
sudo: required

script:
    - dotnet restore
    - dotnet build src/GovITHub.Auth.Common
    - dotnet build src/GovITHub.Auth.Identity
    - dotnet build src/GovITHub.Auth.Admin

    - dotnet test test/GovITHub.Auth.Common.Tests -c Release -f netcoreapp1.0
    - mono \ test/GovITHub.Auth.Common.Tests/bin/Release/net451/*/dotnet-test-xunit.exe \ test/GovITHub.Auth.Common.Tests/bin/Release/net451/*/GovITHub.Auth.Common.Tests.dll